brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/", TodoListUpdateView.as_view(), name="todo_list_update"
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/",
        TodoItemCreateView.as_view(),
        name="todo_item_create",
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now=False, null=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(auto_now=False, null=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from todos.models import TodoList, TodoItem


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_update", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/items/new.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create</title>
    </head>
    <body>
        <main>
                <h1>Create a new list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                      <button class="button">Create</button>
                    </form>
                    </div>
                </main>
            </body>
            </html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>To Do</title>
    </head>
    <body>
        <main>
            <div class="delete-form">
                <form method="post">
                  {% csrf_token %}
                  <p>Are you sure you want to delete "{{ todos }}"?</p>
                  {{ form.as_p }}
                  <div>
                    <button class="button">Delete</button>
                  </div>
                </form>
              </div>
            </main>
        </body>
        </html>
    

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>To Do</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Tasks</h1>
                <p>
                    <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
                </p>
                <p>
                    <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
                </p>
                <table>
                    <thead>
                        <tr>
                            <th>Task</th>
                            <th>Due Date</th>
                        </tr>
                        <tbody>
                            {% for item in todolist.items.all %}
                            <tr>
                                <td><a href="{% url 'todo_item_update' item.pk %}">{{ item.task }}</a>
                                </td>
                                <td>{{ item.due_date }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </thead>
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create</title>
    </head>
    <body>
        <main>
                <h1>Update list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                      <button class="button">Update</button>
                    </form>
                    </div>
                </main>
            </body>
            </html>

todos/templates/todos/items/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Update</title>
    </head>
    <body>
        <main>
                <h1>Update item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                      <button>Update</button>
                    </form>  
                </main>
            </body>
            </html>

todos/templates/todos/items/new.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create</title>
    </head>
    <body>
        <main>
                <h1>Create a new item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                      <button>Create</button>
                    </form>  
                </main>
            </body>
            </html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todos</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <p>
                    <a href="{% url 'todo_list_create' %}">
                        Create a new list</a>
                </p>
                <p>
                    <a href="{% url 'todo_item_create' %}">
                        Create a new item</a>
                </p>
                <table>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                    <tbody>
                        {% for item in todolist_list %}
                    <tr>
                        <td>
                        <a href="{% url 'todo_list_detail' item.pk %}">
                            {{ item.name }}
                        </a>
                        </td>
                        <td>{{ item.items.all|length }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>